apiVersion: 1.0.0
kind: AssuranceProcedure
procedure:
  nrn: "nrn:procedure:nape-tutorials/tutorial-1:new-employee"
  short: "New Employee Assurance Procedure"
  description: |
    "This procedure verifies that a new employee has completed and pass their Criminal History reviews, has signed all
    required documents, and completed the onboarding training and pass with the correct scores."
activity:
  - name: peer-review
    short: "Peer Review"
    description: "This activity verifies that proper peer review controls are in place for a merge into main."
    action:
      - name: atleast-two-pr-reviewers
        short: "Atleast Two Reviewers"
        description: "There are atleast two (2) folks who reviewed the pull request."
        test: "activity/peer-review/atleast-two-reviewers.py"
        evidence: "evidence/peer-review/github-pr.json"

